apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  CART_URL: "http://cart-service:8000"
  CATALOG_URL: "http://catalog-service:8000"
  PAYMENT_URL: "http://payment-service:8000"
  SHIPPING_FLAT_RATE: "25"
  FREE_SHIPPING_THRESHOLD: "300"