services:
  auth-service:
    image:
      tag: "0.1.0-4d07aa6"
  cart-service:
    image:
      tag: "0.1.0-d2b47cb"
  catalog-service:
    image:
      tag: "0.1.0-1731467"
  gateway:
    image:
      tag: "0.1.0-9feac67"
  order-service:
    image:
      tag: "0.1.0-abb8a7c"
  payment-service:
    image:
      tag: "0.1.0-a154c07"
  frontend:
    image:
      tag: "0.1.0-bb8d51a"
