services:
  auth-service:
    image:
      tag: "0.1.0-be7a546"
  cart-service:
    image:
      tag: "0.1.0-a5e00ff"
  catalog-service:
    image:
      tag: "0.1.0-eeffd1d"
  gateway:
    image:
      tag: "0.1.0-9feac67"
  order-service:
    image:
      tag: "0.1.0-be66a19"
  payment-service:
    image:
      tag: "0.1.0-961e10f"
  frontend:
    image:
      tag: "0.1.0-bb8d51a"
