apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets-eso
  namespace: sports-store
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: sports-store/production
        property: JWT_SECRET
    - secretKey: AUTH_MONGO_URI
      remoteRef:
        key: sports-store/production
        property: AUTH_MONGO_URI
    - secretKey: CATALOG_MONGO_URI
      remoteRef:
        key: sports-store/production
        property: CATALOG_MONGO_URI
    - secretKey: CART_MONGO_URI
      remoteRef:
        key: sports-store/production
        property: CART_MONGO_URI
    - secretKey: ORDER_MONGO_URI
      remoteRef:
        key: sports-store/production
        property: ORDER_MONGO_URI
    - secretKey: PAYMENT_MONGO_URI
      remoteRef:
        key: sports-store/production
        property: PAYMENT_MONGO_URI
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-credentials-eso
  namespace: sports-store
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mongodb-credentials
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: sports-store/production
        property: MONGO_ROOT_PASSWORD
    - secretKey: mongodb-passwords
      remoteRef:
        key: sports-store/production
        property: MONGO_ROOT_PASSWORD
