apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.app.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "sports-store.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.app.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
