apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-secrets-sa
  namespace: sports-store
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::765858872029:role/sports-store-external-secrets-role
