namespace:
  create: true
  name: sports-store

global:
  imagePullPolicy: Always
  security:
    allowInsecureImages: true

services:
  auth-service:
    enabled: true
    replicaCount: 1
    image:
      repository: 765858872029.dkr.ecr.us-east-1.amazonaws.com/sports-store-auth-service
      tag: latest
    containerPort: 8000
    service:
      type: ClusterIP
      port: 8000
    configMap: auth-config
    secretName: app-secrets
    env:
      config:
        ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      secrets:
        MONGO_URI: AUTH_MONGO_URI
        JWT_SECRET: JWT_SECRET
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  catalog-service:
    enabled: true
    replicaCount: 1
    image:
      repository: 765858872029.dkr.ecr.us-east-1.amazonaws.com/sports-store-catalog-service
      tag: latest
    containerPort: 8000
    service:
      type: ClusterIP
      port: 8000
    secretName: app-secrets
    env:
      secrets:
        MONGO_URI: CATALOG_MONGO_URI
        JWT_SECRET: JWT_SECRET
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  cart-service:
    enabled: true
    replicaCount: 1
    image:
      repository: 765858872029.dkr.ecr.us-east-1.amazonaws.com/sports-store-cart-service
      tag: latest
    containerPort: 8000
    service:
      type: ClusterIP
      port: 8000
    configMap: cart-config
    secretName: app-secrets
    env:
      config:
        CATALOG_URL: "http://catalog-service:8000"
      secrets:
        MONGO_URI: CART_MONGO_URI
        JWT_SECRET: JWT_SECRET
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  order-service:
    enabled: true
    replicaCount: 1
    image:
      repository: 765858872029.dkr.ecr.us-east-1.amazonaws.com/sports-store-order-service
      tag: latest
    containerPort: 8000
    service:
      type: ClusterIP
      port: 8000
    configMap: order-config
    secretName: app-secrets
    env:
      config:
        CART_URL: "http://cart-service:8000"
        CATALOG_URL: "http://catalog-service:8000"
        PAYMENT_URL: "http://payment-service:8000"
        SHIPPING_FLAT_RATE: "25"
        FREE_SHIPPING_THRESHOLD: "300"
      secrets:
        MONGO_URI: ORDER_MONGO_URI
        JWT_SECRET: JWT_SECRET
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  payment-service:
    enabled: true
    replicaCount: 1
    image:
      repository: 765858872029.dkr.ecr.us-east-1.amazonaws.com/sports-store-payment-service
      tag: latest
    containerPort: 8000
    service:
      type: ClusterIP
      port: 8000
    configMap: payment-config
    secretName: app-secrets
    env:
      config:
        PAYMENT_FAILURE_SUFFIX: "fail"
      secrets:
        MONGO_URI: PAYMENT_MONGO_URI
        JWT_SECRET: JWT_SECRET
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  gateway:
    enabled: true
    replicaCount: 1
    image:
      repository: 765858872029.dkr.ecr.us-east-1.amazonaws.com/sports-store-gateway
      tag: latest
    containerPort: 80
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: "alb"
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/group.name: sportsstore
        alb.ingress.kubernetes.io/group.order: "10"
        alb.ingress.kubernetes.io/healthcheck-path: /health
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:765858872029:certificate/9b33a59c-3ac2-47b7-a2f7-6373887377e3
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
        alb.ingress.kubernetes.io/ssl-redirect: '443'
      hosts:
        - host: sportsstore.seansite.org
          paths:
            - path: /
              pathType: Prefix
    env: {}
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

secrets:
  create: false
  app:
    name: app-secrets

mongodb:
  enabled: true
  image:
    registry: docker.io
    repository: library/mongo
    tag: "8.0"
  auth:
    enabled: true
    rootUser: root
    existingSecret: mongodb-credentials
  architecture: standalone
  initdbScriptsConfigMap: "mongo-init"
  persistence:
    enabled: false
  extraEnvVars:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: "root"
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-credentials
          key: mongodb-root-password
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
  podSecurityContext:
    enabled: true
    runAsUser: 0
  containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    capabilities:
      drop: []
      add:
        - CHOWN
        - SETUID
        - SETGID
        - DAC_OVERRIDE
